# Generated by Django 4.2.2 on 2023-06-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomes', models.CharField(max_length=150)),
                ('Equipamento', models.CharField(max_length=150)),
                ('Setor', models.CharField(max_length=100)),
                ('Grupo', models.CharField(max_length=100)),
            ],
        ),
    ]
